version: 1
disable_existing_loggers: False
formatters:
  console:
    format: "%(asctime)s - %(levelname)-8s - %(name)-15s - %(funcName)-15s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  file:
    format: "%(asctime)s - %(levelname)-8s - %(name)-15s - %(funcName)-15s - %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: DEBUG
    formatter: console
  file:
    (): mule.logging.TimestampFileHandler
    encoding: utf8
    level: INFO
    formatter: file
root:
  level: DEBUG
  handlers: [console, file]
